project_name: apono-cli
before:
  hooks:
    - go mod tidy

builds:
  - id: apono
    binary: apono
    main: ./cmd/apono
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
    flags:
      - -trimpath
    asmflags:
      - all=-trimpath={{ if index .Env "GITHUB_WORKSPACE"  }}{{.Env.GITHUB_WORKSPACE}}{{ else }}{{.Env.PWD}}{{ end }}
    gcflags:
      - all=-trimpath={{ if index .Env "GITHUB_WORKSPACE"  }}{{.Env.GITHUB_WORKSPACE}}{{ else }}{{.Env.PWD}}{{ end }}
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: windows
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  prerelease: auto
